# Generated by Django 4.2 on 2023-06-02 20:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_transfer_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='transfer_pictures'),
        ),
    ]
