# Generated by Django 4.2 on 2023-06-09 09:10

import cloudinary.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='activity_images/')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], unique=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='financial_statements/')),
            ],
        ),
        migrations.CreateModel(
            name='Practitioner',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('cid', models.CharField(max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(11)])),
                ('name', models.CharField(max_length=255)),
                ('profile_pic', cloudinary.models.CloudinaryField(default='profile-icon-login-head-icon-vector_teheof.jpg', max_length=255, verbose_name='profile_pics')),
                ('bob', models.DateField()),
                ('responsibility', models.CharField(max_length=255)),
                ('present_address', models.CharField(max_length=255)),
                ('contact_no', models.CharField(validators=[django.core.validators.MinLengthValidator(8)])),
                ('village', models.CharField(max_length=255)),
                ('card_no', models.CharField(max_length=50)),
                ('tshogchung', models.CharField(max_length=255)),
                ('geog', models.CharField(max_length=255)),
                ('dzongkhag', models.CharField(max_length=255)),
                ('stage_of_threma', models.CharField(blank=True, choices=[('Chapdro', 'Chapdro'), ('Semkey', 'Semkey'), ('Mendray', 'Mendray'), ('Yoenla Dinpa', 'Yoenla Dinpa'), ('Ku Sum Domdey', 'Ku Sum Domdey'), ('Lami Nyelijor', 'Lami Nyelijor')], max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Semso',
            fields=[
                ('semso_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('event', models.CharField(max_length=100)),
                ('contributor', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('practitioner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.practitioner')),
                ('reason', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('picture', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='transfer_pictures')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutiveMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('cid', models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11)])),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('MANAGER', 'Manager'), ('CHAIRPERSON', 'Chairperson'), ('TREASURER', 'Treasurer'), ('ADMIN', 'Admin')], max_length=20)),
                ('responsibility', models.CharField(max_length=255)),
                ('present_address', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8)])),
                ('card_no', models.CharField(max_length=255)),
                ('village', models.CharField(max_length=255)),
                ('geog', models.CharField(max_length=255)),
                ('dzongkhag', models.CharField(max_length=255)),
                ('profile_pic', cloudinary.models.CloudinaryField(default='profile-icon-login-head-icon-vector_teheof.jpg', max_length=255, verbose_name='profile_pics')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Executive Member',
                'verbose_name_plural': 'Executive Members',
            },
        ),
    ]
