# Generated by Django 4.2 on 2023-05-01 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practitioner',
            name='password',
        ),
    ]
