# Generated by Django 4.2 on 2023-05-24 23:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practitioner',
            name='cid',
            field=models.CharField(unique=True, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
    ]
