# Generated by Django 4.2 on 2023-06-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_transfer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='transfer_pictures'),
        ),
    ]
