# Generated by Django 4.2 on 2023-05-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_executivemember_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(max_length=20)),
                ('present_address', models.TextField()),
                ('reason', models.CharField(max_length=200)),
            ],
        ),
    ]
