# Generated by Django 4.2 on 2023-05-24 23:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_practitioner_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practitioner',
            name='contact_no',
            field=models.CharField(validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
