# Generated by Django 4.2 on 2023-05-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_transferform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferform',
            name='cid',
            field=models.CharField(max_length=11),
        ),
    ]
