# Generated by Django 4.2 on 2023-06-09 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_semso_id_semso_semso_id'),
    ]

    operations = [
    ]
