# Generated by Django 4.2 on 2023-05-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_transferform_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferform',
            name='present_address',
            field=models.CharField(),
        ),
    ]
