# Generated by Django 4.2 on 2023-05-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_transferform_present_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferform',
            name='present_address',
            field=models.CharField(max_length=200),
        ),
    ]
