# Generated by Django 4.2 on 2023-05-21 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_transferform_present_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='practitioner',
            name='stage_of_threma',
            field=models.CharField(choices=[('Chapdro', 'Chapdro'), ('Semkey', 'Semkey'), ('Mendray', 'Mendray'), ('Yoenla Dinpa', 'Yoenla Dinpa'), ('Ku Sum Domdey', 'Ku Sum Domdey'), ('Lami Nyelijor', 'Lami Nyelijor')], default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
