# Generated by Django 4.2 on 2023-05-22 15:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_semso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executivemember',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='profile_pics'),
        ),
    ]
