# Generated by Django 4.2 on 2023-06-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_practitioner_bob_practitioner_card_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practitioner',
            name='bob',
            field=models.DateField(max_length=100),
        ),
    ]
