# Generated by Django 4.2 on 2023-05-22 15:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_activity_image_alter_financialstatement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executivemember',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.personality-insights.com%2Fdefault-profile-pic%2F&psig=AOvVaw05weK3HVtZw68bQ5ekVMuw&ust=1684855572822000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCJCAiqOeif8CFQAAAAAdAAAAABAD', max_length=255, verbose_name='profile_pics'),
        ),
    ]
