# Generated by Django 4.2 on 2023-06-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_practitioner_bob'),
    ]

    operations = [
        migrations.AddField(
            model_name='practitioner',
            name='tshogchung',
            field=models.CharField(default=5, max_length=255),
            preserve_default=False,
        ),
    ]
